import { createClient } from "@sanity/client";

const client = createClient({
  projectId: "oe7hnrwl",
  dataset: "production",
  apiVersion: "2024-01-01",
  token: "skEDqZV4mUe6k2wleb9dFLCRlZ8kgcGpUAxs3gNewQUFRo03xvelPKah3oQULct72Ac6ZNcS9KmRPcMBe7wbznckPN5vlW3KmVqEW8hauNwDi0zTdZqXmnCqnzqw4OgqmexVA81hkHUB5HZQO6XFmRhklYwxXyArH30PbDN3bMNsLpw7nnjN",
  useCdn: false,
});

const useCases = [
  { id: "ing-bank-budget", client: "ING Bank", domain: "ing.com", industry: "Banking & Finance", project: "Integrated Budget Planning & Forecasting Platform", technologies: ["IBM Cognos TM1", "IBM Planning Analytics", "REST API"], summary: "Designed and implemented an integrated budget planning and forecasting platform for ING Bank Turkey, consolidating over 30 budget templates into a unified Planning Analytics workspace.", results: "Reduced budget cycle from 6 weeks to 10 days. Eliminated manual Excel consolidation for 200+ users. Achieved single version of financial truth across all business lines." },
  { id: "ing-bank-hr", client: "ING Bank", domain: "ing.com", industry: "Banking & Finance", project: "HR Analytics & Workforce Planning", technologies: ["IBM Cognos TM1", "IBM Planning Analytics", "SQL Server"], summary: "Built a comprehensive HR analytics and workforce planning solution enabling ING Bank Turkey's HR department to model headcount scenarios, track personnel costs, and align workforce plans with financial budgets.", results: "Provided HR and Finance a shared platform for headcount planning. Enabled 'what-if' modelling for salary increase scenarios and hiring plans." },
  { id: "halkbank", client: "Halkbank", domain: "halkbank.com.tr", industry: "Banking & Finance", project: "Financial Consolidation & Regulatory Reporting", technologies: ["IBM Cognos Controller", "IBM Cognos Analytics", "Oracle"], summary: "Implemented IBM Cognos Controller for group-level financial consolidation across Halkbank and its subsidiaries, enabling automated intercompany eliminations, currency translation, and regulatory reporting packages.", results: "Reduced monthly close cycle by 40%. Automated BRSA regulatory report generation. Enabled consolidated balance sheet in real time." },
  { id: "akbank-argus", client: "Akbank", domain: "akbank.com", industry: "Banking & Finance", project: "ARGUS – Enterprise Risk & Performance Analytics Platform", technologies: ["IBM Cognos Analytics", "IBM Planning Analytics", "Python", "Oracle"], summary: "Led the end-to-end delivery of ARGUS — Akbank's enterprise risk and performance analytics platform. The platform integrates credit risk, market risk, and financial performance data into a single analytical layer.", results: "Single integrated risk/finance data mart serving 500+ internal users. Real-time Basel III capital ratio monitoring. 60% reduction in manual report preparation." },
  { id: "alternatif-bank", client: "Alternatif Bank", domain: "alternatifbank.com.tr", industry: "Banking & Finance", project: "Branch Performance & Profitability Analytics", technologies: ["IBM Cognos Analytics", "IBM Planning Analytics"], summary: "Delivered a branch-level performance and profitability analytics solution for Alternatif Bank, enabling management to evaluate revenue, cost, and risk metrics at granular branch and product levels.", results: "Enabled product-level P&L visibility at branch level. Improved banker incentive calculations accuracy." },
  { id: "ziraat-bank", client: "Ziraat Bank", domain: "ziraatbank.com.tr", industry: "Banking & Finance", project: "Enterprise Data Warehouse & BI Platform", technologies: ["IBM InfoSphere", "IBM Cognos Analytics", "Teradata"], summary: "Architected and implemented the enterprise data warehouse and BI platform for Ziraat Bank, Turkey's largest bank by assets.", results: "Consolidated 15+ source systems into a single EDW. Enabled self-service analytics for 300+ business users." },
  { id: "iyzico", client: "IYZICO", domain: "iyzico.com", industry: "Banking & Finance", project: "Payment Analytics & Merchant Intelligence Dashboard", technologies: ["Tableau", "Databricks", "AWS S3", "Python"], summary: "Built a real-time payment analytics and merchant intelligence dashboard for IYZICO, enabling the fintech company to monitor transaction volumes, detect anomalies, and provide merchants with performance insights.", results: "Real-time transaction monitoring across 10,000+ merchants. 30% improvement in fraud detection response time." },
  { id: "vakifbank-crm", client: "VakıfBank", domain: "vakifbank.com.tr", industry: "Banking & Finance", project: "Customer Analytics & CRM Intelligence Platform", technologies: ["IBM Cognos Analytics", "Python", "Oracle"], summary: "Built a customer analytics and CRM intelligence platform for VakıfBank, enabling relationship managers to identify cross-sell opportunities, track customer profitability, and segment the customer base for targeted campaigns.", results: "Cross-sell conversion rates improved by 28%. Customer profitability scoring deployed to 15M+ customers." },
  { id: "vakifbank-risk", client: "VakıfBank", domain: "vakifbank.com.tr", industry: "Banking & Finance", project: "Credit Risk Analytics & IFRS 9 Reporting", technologies: ["IBM Cognos Analytics", "Python", "Oracle", "SAS"], summary: "Implemented credit risk analytics and IFRS 9 reporting capabilities for VakıfBank, automating the calculation of Expected Credit Loss (ECL) provisions, Stage classification, and regulatory disclosures.", results: "IFRS 9 reporting cycle reduced from 3 weeks to 4 days. ECL model validated and approved by external auditors." },
  { id: "fibabanka", client: "Fibabanka", domain: "fibabanka.com", industry: "Banking & Finance", project: "Enterprise Data Warehouse & Management Reporting", technologies: ["IBM Cognos Analytics", "Teradata", "SQL Server"], summary: "Designed and implemented the enterprise data warehouse and management reporting platform for Fibabanka, consolidating retail, commercial, and treasury data to provide executive and board-level reporting.", results: "Single EDW serving all management reporting needs. Monthly management pack automated reducing preparation time by 70%." },
  { id: "nn-life", client: "NN Life", domain: "nn.com.tr", industry: "Insurance", project: "Actuarial & Financial Planning Platform", technologies: ["IBM Planning Analytics", "TM1", "SQL Server"], summary: "Implemented an actuarial and financial planning platform for NN Life Turkey, automating the translation of actuarial projections into financial plans and enabling dynamic scenario modelling.", results: "Reduced actuarial-to-finance reporting cycle by 50%. Enabled monthly rolling forecast with scenario comparison." },
  { id: "mapfre", client: "Mapfre", domain: "mapfre.com.tr", industry: "Insurance", project: "Claims Analytics & Loss Ratio Optimization", technologies: ["IBM Cognos Analytics", "IBM Planning Analytics", "Oracle"], summary: "Delivered a claims analytics solution for Mapfre Turkey, providing actuaries and claims managers with deep visibility into loss ratios, claims frequency, and reserve adequacy across all product lines.", results: "Identified 15% improvement opportunity in claims reserves. Reduced loss ratio reporting time from 2 weeks to 2 days." },
  { id: "sompo-sigorta", client: "Sompo Sigorta", domain: "sompo.com.tr", industry: "Insurance", project: "Reinsurance Analytics & Treaty Management", technologies: ["Tableau", "SQL Server", "Python"], summary: "Built a reinsurance analytics and treaty management dashboard for Sompo Sigorta, enabling underwriters and reinsurance managers to track cession rates, recoveries, and net retained risk.", results: "Full visibility into reinsurance program performance. Automated cession calculation reducing errors by 90%." },
  { id: "commonwealth-care-alliance", client: "Commonwealth Care Alliance", domain: "commonwealthcare.org", industry: "Insurance", project: "Population Health Management & Risk Stratification Platform", technologies: ["Databricks", "Python", "Tableau", "AWS"], summary: "Developed a population health management and risk stratification platform for Commonwealth Care Alliance, enabling care managers to identify high-risk members and predict hospitalizations.", results: "15% reduction in preventable hospital admissions. Identified 8,000 high-risk members for proactive care management. $12M estimated savings in year 1." },
  { id: "vodafone", client: "Vodafone", domain: "vodafone.com", industry: "Telecom", project: "Customer Lifetime Value & Churn Prediction Platform", technologies: ["Databricks", "Python", "Spark", "Tableau", "AWS"], summary: "Designed and deployed a customer lifetime value scoring and churn prediction platform for Vodafone Turkey, leveraging machine learning models to identify at-risk customers and optimize retention campaigns.", results: "15% reduction in voluntary churn for targeted segments. CLV model deployed to 25M+ active subscribers. 3x improvement in retention campaign ROI." },
  { id: "charter-communications", client: "Charter Communications", domain: "charter.com", industry: "Telecom", project: "Subscriber Analytics & Network Performance Dashboard", technologies: ["Tableau", "Databricks", "AWS Redshift", "Python"], summary: "Implemented a subscriber analytics and network performance dashboard for Charter Spectrum, integrating billing, network, and customer service data.", results: "Reduced average handle time by 20% through better agent dashboards. Network-to-billing correlation enabled 25% faster fault resolution." },
  { id: "turk-telekom", client: "Türk Telekom", domain: "turktelekom.com.tr", industry: "Telecom", project: "Enterprise Financial Planning & Consolidation", technologies: ["IBM Planning Analytics", "IBM Cognos Controller"], summary: "Implemented enterprise financial planning and consolidation for Türk Telekom Group, covering budget planning, quarterly forecasting, and statutory consolidation across the group's 10+ legal entities.", results: "Group consolidation cycle reduced from 15 days to 4 days. Automated IFRS adjustment calculations." },
  { id: "haleon", client: "Haleon", domain: "haleon.com", industry: "Pharma & Biotech", project: "Commercial Analytics & Market Intelligence Platform", technologies: ["Tableau", "Databricks", "Alteryx", "AWS"], summary: "Built a global commercial analytics and market intelligence platform for Haleon, integrating sell-in, sell-out, market share, and competitor data across 25 markets.", results: "25 markets on single platform. 40% reduction in time-to-insight for commercial decisions. Automated data refresh replacing 80+ manual Excel reports." },
  { id: "roche-forecasting", client: "Roche", domain: "roche.com", industry: "Pharma & Biotech", project: "Global Demand Forecasting & Supply Chain Analytics", technologies: ["Databricks", "Python", "Tableau", "Azure"], summary: "Developed a global demand forecasting and supply chain analytics platform for Roche, combining statistical forecasting models with market intelligence to improve supply planning accuracy for 40+ oncology products.", results: "Forecast accuracy improved by 22%. Inventory holding costs reduced by $18M annually. Automated consensus forecasting process." },
  { id: "roche-patient", client: "Roche", domain: "roche.com", industry: "Pharma & Biotech", project: "Patient Journey Analytics", technologies: ["Databricks", "Python", "Tableau", "Azure"], summary: "Designed a patient journey analytics solution for Roche, mapping treatment pathways, time-to-treatment, and therapy switching patterns using real-world evidence data from US healthcare claims.", results: "Identified 3 key intervention points to improve patient outcomes. Informed commercial strategy for new product launch." },
  { id: "novartis", client: "Novartis", domain: "novartis.com", industry: "Pharma & Biotech", project: "Integrated Commercial Reporting Platform", technologies: ["Tableau", "Alteryx", "AWS S3", "Python"], summary: "Implemented an integrated commercial reporting platform for Novartis Turkey, consolidating sales force activity, market access, and market share data.", results: "Brand performance reporting reduced from weekly manual process to daily automated updates. Sales force deployment optimized based on territory analytics." },
  { id: "amgen", client: "Amgen", domain: "amgen.com", industry: "Pharma & Biotech", project: "Rare Disease Patient Identification & Market Access Analytics", technologies: ["Python", "Tableau", "Databricks", "AWS"], summary: "Built a patient identification and market access analytics platform for Amgen's rare disease portfolio, using claims data and physician-level analytics.", results: "Identified 40% more eligible patients versus traditional methods. Reduced time to first prescription by 30 days on average." },
  { id: "electrocore", client: "ElectroCore", domain: "electrocore.com", industry: "Pharma & Biotech", project: "Real-World Evidence Analytics Platform", technologies: ["Python", "Tableau", "AWS", "SQL"], summary: "Built a real-world evidence analytics platform for ElectroCore, aggregating clinical trial data, EHR extracts, and claims data to demonstrate the real-world effectiveness of vagus nerve stimulation therapy.", results: "RWE package supporting payer submissions in 5 markets. 60% improvement in payer engagement outcomes." },
  { id: "coca-cola", client: "Coca-Cola", domain: "coca-cola.com", industry: "Retail", project: "Route-to-Market Analytics & Sales Force Effectiveness", technologies: ["Tableau", "Alteryx", "SQL Server", "Python"], summary: "Delivered a route-to-market analytics and sales force effectiveness platform for Coca-Cola Turkey, enabling territory managers to optimize outlet coverage and track cooler performance.", results: "Sales force coverage improved by 18%. Cooler asset utilization increased by 25%. Route optimization reduced logistics costs by 12%." },
  { id: "koctas", client: "Koçtaş", domain: "koctas.com.tr", industry: "Retail", project: "Retail Analytics & Store Performance Platform", technologies: ["IBM Cognos Analytics", "SQL Server", "Oracle Retail"], summary: "Implemented a retail analytics and store performance platform for Koçtaş, integrating POS, inventory, and CRM data to provide store managers and category teams with real-time performance visibility.", results: "Store-level P&L visibility for 120+ stores. Category performance insights reduced slow-moving inventory by 20%." },
  { id: "pepsi", client: "Pepsi (Frito-Lay)", domain: "pepsi.com", industry: "Retail", project: "Trade Promotion Analytics & ROI Measurement", technologies: ["Alteryx", "Tableau", "SQL Server"], summary: "Built a trade promotion analytics and ROI measurement solution for Frito-Lay Turkey, enabling the commercial team to evaluate the incremental impact of promotions and optimize trade investment allocation.", results: "Trade promotion ROI improved by 22%. Promotion evaluation time reduced from 3 weeks to 2 days." },
  { id: "balparmak", client: "Balparmak", domain: "balparmak.com.tr", industry: "Retail", project: "Supply Chain & Distribution Analytics", technologies: ["Tableau", "SQL Server", "Python"], summary: "Built supply chain and distribution analytics for Balparmak, Turkey's largest honey brand, enabling the company to optimize inventory levels, track distributor performance, and improve demand-supply matching.", results: "Inventory turnover improved by 15%. Distributor performance visibility enabled 10% reduction in stockouts." },
  { id: "oyak-cement", client: "OYAK Cement", domain: "oyak.com.tr", industry: "Manufacturing", project: "Group Financial Consolidation & Performance Reporting", technologies: ["IBM Cognos Controller", "IBM Planning Analytics"], summary: "Implemented group financial consolidation and performance reporting for OYAK Cement Group, covering statutory consolidation, management reporting, and KPI dashboards across 8 cement plants.", results: "Consolidated reporting reduced from 20 days to 5 days. Standardized KPI framework across all plants." },
  { id: "enerjisa", client: "Enerjisa", domain: "enerjisa.com.tr", industry: "Manufacturing", project: "Energy Analytics & Grid Performance Platform", technologies: ["Databricks", "Python", "Tableau", "Azure"], summary: "Developed an energy analytics and grid performance platform for Enerjisa, enabling real-time monitoring of grid performance, outage prediction, and demand forecasting.", results: "Outage prediction accuracy improved by 35%. Demand forecasting error reduced by 18%. Enabled predictive maintenance scheduling." },
  { id: "zorlu", client: "Zorlu", domain: "zorlu.com.tr", industry: "Manufacturing", project: "Manufacturing Performance & OEE Analytics", technologies: ["IBM Cognos Analytics", "SQL Server", "SAP integration"], summary: "Implemented a manufacturing performance and OEE analytics platform for Zorlu Group, connecting shop-floor data with financial KPIs.", results: "OEE improved by 8% through data-driven maintenance scheduling. Integration of SAP and shop-floor data eliminated manual reporting." },
  { id: "mng-kargo", client: "MNG Kargo", domain: "mngkargo.com.tr", industry: "Other", project: "Logistics Network Analytics & Last-Mile Optimization", technologies: ["Databricks", "Python", "Tableau", "AWS"], summary: "Designed a logistics network analytics and last-mile optimization platform for MNG Kargo, enabling operations managers to analyze route efficiency and optimize courier allocation across 80+ distribution hubs.", results: "On-time delivery rate improved by 12%. Courier productivity increased by 18%. Fuel costs reduced by 9% through route optimization." },
  { id: "digiturk", client: "Digiturk", domain: "digiturk.com.tr", industry: "Media", project: "Subscriber Analytics & Content Performance Platform", technologies: ["Tableau", "Databricks", "AWS", "Python"], summary: "Built a subscriber analytics and content performance platform for Digiturk, Turkey's leading pay-TV operator, enabling the marketing team to analyze viewing behavior and measure content ROI.", results: "Churn prediction model reduced voluntary churn by 18%. Content investment decisions informed by 50M+ viewing events per day." },
  { id: "siriusxm", client: "SiriusXM", domain: "siriusxm.com", industry: "Media", project: "Subscriber Lifetime Value & Retention Analytics", technologies: ["Databricks", "Python", "Tableau", "AWS Redshift"], summary: "Developed a subscriber lifetime value and retention analytics platform for SiriusXM, enabling the data science team to build CLV models and identify churn risk segments.", results: "CLV model accuracy improved by 30%. Retention program ROI increased by $45M annually. Automated A/B test analysis framework." },
  { id: "istanbul-municipality", client: "Istanbul Metropolitan Municipality", domain: "ibb.gov.tr", industry: "Government", project: "Smart City Analytics & Urban Performance Dashboard", technologies: ["IBM Cognos Analytics", "ArcGIS", "SQL Server"], summary: "Implemented a smart city analytics and urban performance dashboard for Istanbul Metropolitan Municipality, integrating data from transportation, utilities, public services, and citizen feedback channels.", results: "Unified view of 50+ city services in single dashboard. Decision-making cycle for urban investments reduced by 40%." },
];

const teamMembers = [
  { id: "kutlay", name: "Kutlay Erdal Şimşek", title: "CEO & Founder", order: 1, linkedIn: "https://www.linkedin.com/in/kutlay-simsek-930358/", groups: ["leadership", "partners_board"] },
  { id: "burak", name: "Burak Tansug", title: "Technology Services & Operations", region: "US", order: 2, linkedIn: "https://www.linkedin.com/in/buraktansug/", groups: ["leadership", "partners_board"] },
  { id: "murat", name: "Murat Destegül", title: "Technology Services & Operations", region: "TR", order: 3, linkedIn: "https://www.linkedin.com/in/muratdestegul/", groups: ["leadership", "partners_board"] },
  { id: "abdulkadir", name: "Abdulkadir Kesimli", title: "Product & R&D", order: 4, linkedIn: "https://www.linkedin.com/in/abdulkadir-kesimli/", groups: ["leadership", "partners_board"] },
  { id: "kerem", name: "Kerem Arıtürk", title: "Revenue & Growth", order: 5, linkedIn: "https://www.linkedin.com/in/keremariturk/", groups: ["leadership", "partners_board"] },
  { id: "berrin", name: "Berrin Şimşek", title: "Finance & People", order: 6, linkedIn: "https://www.linkedin.com/in/berrin-%C5%9Fim%C5%9Fek-2b602973/", groups: ["leadership", "partners_board"] },
  { id: "demirhan", name: "Demirhan Yenigün", title: "Partner", order: 7, linkedIn: "https://www.linkedin.com/in/demirhan-yenigun-ph-d-0782573/", groups: ["partners_board"] },
  { id: "mustafa", name: "Mustafa Tosun", title: "Partner", order: 8, linkedIn: "https://www.linkedin.com/in/mustafatosun/", groups: ["partners_board"] },
  { id: "metin", name: "Metin Ergün", title: "Partner", order: 9, linkedIn: null, groups: ["partners_board"] },
  { id: "hande", name: "Hande Ölmez", title: "Partner", order: 10, linkedIn: "https://www.linkedin.com/in/hande-o-3b03b4a4/", groups: ["partners_board"] },
];

const partners = [
  { id: "ibm", name: "IBM", description: "Over 20 years of deep IBM ecosystem expertise. Certified in Planning Analytics (TM1), Cognos Analytics, InfoSphere DataStage, IBM CDC, and watsonx. EMEA watsonx Agentic AI Academy participant.", areas: ["Financial Performance Management", "Data Integration", "AI & ML", "Business Intelligence"], useCases: ["ING Bank full FP&A platform", "Akbank ARGUS reporting", "Ziraat Enterprise AI"], order: 1 },
  { id: "aws", name: "AWS", description: "Cloud migrations, data lake architecture, DataOps, and AI deployment on AWS. Active on projects for US pharma, insurance, and biotech clients.", areas: ["Cloud Migration", "Data Lake & Lakehouse", "DataOps", "AI Deployment"], useCases: ["Haleon Secondary Sales Platform", "Roche Data Stack Modernization", "Charter Communications"], order: 2 },
  { id: "hcl", name: "HCL Software", description: "Authorized partner for the full HCL Unica suite and HCL Discover. Implementing omnichannel campaign management, marketing operations, and digital analytics.", areas: ["Campaign Management", "Marketing Operations", "Digital Analytics", "Customer Experience"], useCases: ["VakıfBank omnichannel campaigns", "Fibabanka campaign management", "Turkish Airlines marketing ops"], order: 3 },
  { id: "databricks", name: "Databricks", description: "Lakehouse architecture, MLflow, Delta Lake, and collaborative data engineering on the Databricks platform.", areas: ["Lakehouse Architecture", "MLflow & MLOps", "Delta Lake", "Data Engineering"], useCases: [], order: 4 },
  { id: "alteryx", name: "Alteryx", description: "Data blending, predictive analytics, and automated ETL workflows. Deployed for global pharma and telecom clients.", areas: ["Data Blending", "Predictive Analytics", "Automated ETL", "Self-Service Analytics"], useCases: ["Roche — 50+ warehouses automated", "Charter Communications reporting"], order: 5 },
  { id: "tableau", name: "Tableau", description: "Executive dashboards, self-service analytics, and Tableau Server deployments for enterprise clients across banking, pharma, retail, and telecom.", areas: ["Executive Dashboards", "Self-Service Analytics", "Tableau Server", "Data Visualization"], useCases: ["Vodafone 685-user deployment", "Pepsi executive dashboard", "Halkbank BI platform"], order: 6 },
  { id: "datarobot", name: "DataRobot", description: "Enterprise AutoML, MLOps, and AI platform deployments. Proven ROI on industrial and banking AI use cases.", areas: ["AutoML", "MLOps", "Enterprise AI", "Predictive Modeling"], useCases: ["OYAK Cement — $39M savings, 2% CO₂ reduction", "Ziraat Bank Enterprise AI Platform"], order: 7 },
  { id: "snowflake", name: "Snowflake", description: "Cloud data platform for scalable analytics, data sharing, and modern data engineering.", areas: ["Cloud Data Warehouse", "Data Sharing", "Data Engineering", "Analytics"], useCases: [], order: 8 },
  { id: "apparo", name: "Apparo", description: "Fast Edit and data entry solutions integrated with IBM Planning Analytics and Cognos for streamlined financial data management.", areas: ["Data Entry & Writeback", "IBM PA Integration", "Financial Data Management"], useCases: ["Akbank ARGUS target management", "Roche data management"], order: 9 },
  { id: "theobald", name: "Theobald Software", description: "SAP data extraction and integration, connecting SAP systems with analytics platforms like IBM Planning Analytics and Tableau.", areas: ["SAP Integration", "Data Extraction", "ERP Connectivity"], useCases: ["Enerjisa SAP integration", "Zorlu Holding energy analytics"], order: 10 },
];

const certGroups = [
  { id: "ibm", vendor: "IBM", description: "Over 25 years of deep IBM ecosystem expertise across Planning Analytics, Cognos, DataStage, and watsonx.", certifications: [{ name: "IBM Planning Analytics (TM1) — Expert", level: "Expert", color: "bg-blue-700" }, { name: "IBM Cognos Analytics — Expert", level: "Expert", color: "bg-blue-700" }, { name: "IBM Cognos Controller — Expert", level: "Expert", color: "bg-blue-700" }, { name: "IBM InfoSphere DataStage — Advanced", level: "Advanced", color: "bg-blue-500" }, { name: "IBM Cloud Pak for Data — Certified", level: "Certified", color: "bg-blue-400" }, { name: "IBM Watson — Practitioner", level: "Practitioner", color: "bg-blue-300" }], order: 1 },
  { id: "aws", vendor: "AWS", description: "Certified expertise in designing and delivering analytics, data lake, and AI solutions on Amazon Web Services.", certifications: [{ name: "AWS Certified Solutions Architect — Associate", level: "Associate", color: "bg-orange-500" }, { name: "AWS Certified Data Analytics — Specialty", level: "Specialty", color: "bg-orange-600" }, { name: "AWS Certified Machine Learning — Specialty", level: "Specialty", color: "bg-orange-600" }, { name: "AWS Certified Developer — Associate", level: "Associate", color: "bg-orange-500" }], order: 2 },
  { id: "hcl", vendor: "HCL Software", description: "Authorized partner for the full HCL Unica marketing suite.", certifications: [{ name: "HCL Unica Campaign — Expert", level: "Expert", color: "bg-red-700" }, { name: "HCL Unica Interact — Advanced", level: "Advanced", color: "bg-red-600" }, { name: "HCL Discover — Certified", level: "Certified", color: "bg-red-500" }], order: 3 },
  { id: "alteryx", vendor: "Alteryx", description: "Designer Core and Advanced certifications for data blending and analytics automation.", certifications: [{ name: "Alteryx Designer Core — Certified", level: "Certified", color: "bg-blue-600" }, { name: "Alteryx Designer Advanced — Certified", level: "Certified", color: "bg-blue-700" }, { name: "Alteryx Server — Partner", level: "Partner", color: "bg-blue-500" }], order: 4 },
  { id: "tableau", vendor: "Tableau", description: "Professional-level Tableau Desktop and Server certifications across our team.", certifications: [{ name: "Tableau Desktop Certified Professional", level: "Professional", color: "bg-sky-600" }, { name: "Tableau Server Certified Associate", level: "Associate", color: "bg-sky-500" }, { name: "Tableau Prep Builder — Certified", level: "Certified", color: "bg-sky-400" }, { name: "Tableau CRM & Einstein Analytics", level: "Practitioner", color: "bg-sky-300" }], order: 5 },
  { id: "datarobot", vendor: "DataRobot", description: "Certified in the DataRobot AI platform, enabling automated machine learning and MLOps deployments.", certifications: [{ name: "DataRobot Automated ML — Expert", level: "Expert", color: "bg-violet-600" }, { name: "DataRobot MLOps — Practitioner", level: "Practitioner", color: "bg-violet-500" }, { name: "DataRobot AI Platform", level: "Certified", color: "bg-violet-400" }], order: 6 },
];

async function run() {
  console.log("🚀 Migration başlıyor...\n");

  console.log(`📦 ${useCases.length} success story aktarılıyor...`);
  for (const uc of useCases) {
    await client.createOrReplace({ _type: "successStory", _id: `successStory-${uc.id}`, client: uc.client, domain: uc.domain, industry: uc.industry, project: uc.project, technologies: uc.technologies, summary: uc.summary, results: uc.results });
    process.stdout.write(`  ✓ ${uc.client}\n`);
  }

  console.log(`\n👥 ${teamMembers.length} ekip üyesi aktarılıyor...`);
  for (const m of teamMembers) {
    await client.createOrReplace({ _type: "teamMember", _id: `teamMember-${m.id}`, name: m.name, title: m.title, region: m.region, order: m.order, linkedIn: m.linkedIn, groups: m.groups });
    console.log(`  ✓ ${m.name}`);
  }

  console.log(`\n🤝 ${partners.length} partner aktarılıyor...`);
  for (const p of partners) {
    await client.createOrReplace({ _type: "partner", _id: `partner-${p.id}`, name: p.name, description: p.description, areas: p.areas, useCases: p.useCases, order: p.order });
    console.log(`  ✓ ${p.name}`);
  }

  console.log(`\n🏅 ${certGroups.length} sertifika grubu aktarılıyor...`);
  for (const g of certGroups) {
    await client.createOrReplace({ _type: "certificationGroup", _id: `certGroup-${g.id}`, vendor: g.vendor, description: g.description, certifications: g.certifications, order: g.order });
    console.log(`  ✓ ${g.vendor}`);
  }

  console.log("\n✅ Migration tamamlandı!");
  console.log("   https://ereteam.sanity.studio — içerikleri kontrol et.");
  console.log("   ⚠️  Partner logoları Studio'dan manuel yüklenmelidir.");
}

run().catch((err) => { console.error("❌ Hata:", err.message); process.exit(1); });
